#!/usr/bin/env bash
# generate-image-dimensions.sh — BLOG-017
#
# Builds _data/image_dimensions.yml: a map from each image's site path
# (e.g. /assets/images/foo.png) to its intrinsic { width, height }.
#
# Jekyll cannot read pixel dimensions natively and Gemfile/_config.yml are
# protected (no new plugin), so the map is generated here and COMMITTED — the
# GitHub Pages CI build does not run this script. Re-run after adding or
# replacing images.
#
# Requires: sips (macOS) or ImageMagick `identify` (Linux/CI dev boxes).
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

# Directories that hold images referenced from front matter / content.
IMAGE_DIRS=()
for d in assets/images assets/charts; do
  [[ -d "$d" ]] && IMAGE_DIRS+=("$d")
done
OUT="_data/image_dimensions.yml"

if [[ ${#IMAGE_DIRS[@]} -eq 0 ]]; then
  echo "error: no image directories found (assets/images, assets/charts)" >&2
  exit 1
fi

# Read SVG intrinsic dimensions from the markup: prefer explicit width/height
# attributes (px stripped), else the viewBox "minX minY W H".
read_svg_dims() {
  local f="$1" tag w h
  tag="$(tr '\n' ' ' < "$f" | grep -oE '<svg[^>]*>' | head -1)"
  w="$(printf '%s' "$tag" | grep -oE 'width="[0-9.]+' | head -1 | grep -oE '[0-9.]+')"
  h="$(printf '%s' "$tag" | grep -oE 'height="[0-9.]+' | head -1 | grep -oE '[0-9.]+')"
  if [[ -z "$w" || -z "$h" ]]; then
    read -r w h < <(printf '%s' "$tag" \
      | grep -oE 'viewBox="[^"]*"' | head -1 \
      | grep -oE '[0-9.]+' | awk 'NR==3{x=$1}NR==4{y=$1}END{print x, y}')
  fi
  # round to integers
  [[ -n "$w" && -n "$h" ]] && printf '%.0f %.0f' "$w" "$h"
}

# Pick a dimension reader.
read_dims() {
  # prints "<width> <height>" for the file in $1, or nothing on failure
  local f="$1"
  case "$f" in
    *.svg|*.SVG) read_svg_dims "$f"; return ;;
  esac
  if command -v sips >/dev/null 2>&1; then
    sips -g pixelWidth -g pixelHeight "$f" 2>/dev/null \
      | awk '/pixelWidth/{w=$2}/pixelHeight/{h=$2}END{if(w&&h)print w, h}'
  elif command -v identify >/dev/null 2>&1; then
    identify -format '%w %h' "$f" 2>/dev/null
  else
    echo "error: need sips or ImageMagick identify" >&2
    exit 1
  fi
}

{
  echo "# Generated by scripts/generate-image-dimensions.sh — do not edit by hand."
  echo "# Maps image site paths to intrinsic pixel dimensions (BLOG-017)."
  # Iterate raster sources; key by the path used in front matter.
  while IFS= read -r f; do
    dims="$(read_dims "$f" || true)"
    [[ -z "$dims" ]] && continue
    w="${dims% *}"
    h="${dims#* }"
    path="/${f}"
    printf '"%s":\n  width: %s\n  height: %s\n' "$path" "$w" "$h"
  done < <(find "${IMAGE_DIRS[@]}" -type f \( -iname '*.png' -o -iname '*.jpg' \
              -o -iname '*.jpeg' -o -iname '*.webp' -o -iname '*.svg' \) | sort)
} > "$OUT"

count=$(grep -c '^"' "$OUT" || true)
echo "Wrote $OUT ($count images)"
