#!/usr/bin/env bash
# handoff.sh — generate a session handoff note for resuming in a fresh Copilot session
# Usage: bash scripts/handoff.sh
# Output: ~/.copilot/handoff.md  (load it in a new session with: @~/.copilot/handoff.md)

set -euo pipefail

BLOG="oviney/blog"
AGENTS="oviney/economist-agents"
OUT="${HOME}/.copilot/handoff.md"
NOW=$(date '+%Y-%m-%d %H:%M %Z')

# Also echo to stdout so the agent can read it inline
exec > >(tee "$OUT") 2>&1

echo "# Handoff Note — ${NOW}"
echo ""
echo "> Generated by \`bash scripts/handoff.sh\`."
echo "> To resume: start a fresh \`copilot\` session, then type \`@ ~/.copilot/handoff.md\`"
echo ""

# ── Current branch & recent commits ──────────────────────────────────────────
echo "## Current git state"
echo ""
echo "**Branch:** \`$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo 'unknown')\`"
echo ""
echo "**Recent commits (last 10):**"
git --no-pager log --oneline -10 2>/dev/null | sed 's/^/- /' || echo "- (no commits)"
echo ""

UNCOMMITTED=$(git --no-pager status --short 2>/dev/null || true)
if [[ -n "$UNCOMMITTED" ]]; then
  echo "**Uncommitted changes:**"
  echo '```'
  echo "$UNCOMMITTED"
  echo '```'
  echo ""
fi

# ── Open PRs ─────────────────────────────────────────────────────────────────
echo "## Open PRs"
echo ""
echo "### ${BLOG}"
gh pr list --repo "$BLOG" --state open \
  --json number,title,isDraft,author,updatedAt \
  --jq '.[] | "- #\(.number) \(if .isDraft then "[DRAFT]" else "[READY]" end) \(.title) (\(.author.login)) — \(.updatedAt)"' \
  2>/dev/null || echo "- none"
echo ""

echo "### ${AGENTS}"
gh pr list --repo "$AGENTS" --state open \
  --json number,title,isDraft,author,updatedAt \
  --jq '.[] | "- #\(.number) \(if .isDraft then "[DRAFT]" else "[READY]" end) \(.title) (\(.author.login)) — \(.updatedAt)"' \
  2>/dev/null || echo "- none"
echo ""

# ── Issues assigned to Copilot ────────────────────────────────────────────────
echo "## Issues in flight (assigned to @copilot)"
echo ""
for REPO in "$BLOG" "$AGENTS"; do
  echo "### ${REPO}"
  gh issue list --repo "$REPO" --state open \
    --json number,title,assignees,labels \
    --jq '.[] | select(.assignees | map(.login) | any(. == "Copilot")) | "- #\(.number) [\(.labels | map(.name) | join(", "))] \(.title)"' \
    2>/dev/null || echo "- none"
  echo ""
done

# ── Unassigned P1/P2 issues ───────────────────────────────────────────────────
echo "## Backlog — unassigned P1/P2 issues"
echo ""
for REPO in "$BLOG" "$AGENTS"; do
  echo "### ${REPO}"
  gh issue list --repo "$REPO" --state open \
    --json number,title,labels,assignees \
    --jq '.[] | select((.assignees | length) == 0) | select(.labels | map(.name) | any(test("P1|P2"))) | "- #\(.number) [\(.labels | map(.name) | join(", "))] \(.title)"' \
    2>/dev/null || echo "- none"
  echo ""
done

# ── Session plan (if present) ─────────────────────────────────────────────────
# Look for a plan.md in any session-state folder modified in the last 2 hours
RECENT_PLAN=$(find "${HOME}/.copilot/session-state" -name "plan.md" -mmin -120 2>/dev/null | head -1 || true)
if [[ -n "$RECENT_PLAN" ]]; then
  echo "## Session plan (from active session)"
  echo ""
  cat "$RECENT_PLAN"
  echo ""
fi

# ── How to continue ───────────────────────────────────────────────────────────
echo "## How to continue"
echo ""
echo "1. Merge any READY PRs:"
echo '   ```bash'
echo "   gh pr merge <N> --repo <REPO> --admin --squash --delete-branch"
echo '   ```'
echo "2. Check stalled DRAFT PRs (no new commit in 30 min) → close & reassign:"
echo '   ```bash'
echo "   gh pr view <N> --repo <REPO> --json commits --jq '.commits | map(.messageHeadline)'"
echo "   gh pr close <N> --repo <REPO> --comment 'Stalled — reassigning'"
echo "   gh issue edit <ISSUE> --repo <REPO> --add-assignee '@copilot'"
echo '   ```'
echo "3. Dispatch backlog items:"
echo '   ```bash'
echo "   gh issue edit <N> --repo <REPO> --add-assignee '@copilot'"
echo '   ```'
echo ""
echo "---"
echo "_Handoff saved to \`${OUT}\`_"
